export type District = {
  name: string
  slug: string
  lat: number
  lon: number
  description?: string
  group?: string // borough (NYC) or region label
}

export type City = {
  name: string
  slug: string
  country: string
  flag: string
  lat: number
  lon: number
  timezone: string
  description: string
  districts: District[]
}

export const CITIES: City[] = [
  {
    name: 'New York City',
    slug: 'nyc',
    country: 'United States',
    flag: '🇺🇸',
    lat: 40.7128,
    lon: -74.0060,
    timezone: 'America/New_York',
    description: "New York City's five boroughs each experience distinct microclimates shaped by their proximity to the Atlantic Ocean, Long Island Sound, and the Hudson, East, and Harlem Rivers. Coastal areas stay cooler in summer and face harsher nor'easters in winter, while inland neighborhoods feel the full urban heat island effect.",
    districts: [
      // Manhattan
      { name: 'Midtown', slug: 'midtown', lat: 40.7549, lon: -73.9840, group: 'Manhattan', description: "Midtown's skyscraper canyons create powerful wind tunnels and trap heat, making it warmer in summer and windier in winter than surrounding areas." },
      { name: 'Upper East Side', slug: 'upper-east-side', lat: 40.7736, lon: -73.9566, group: 'Manhattan', description: "The Upper East Side benefits from Central Park's moderating influence to the west and occasional East River breezes from the east." },
      { name: 'Upper West Side', slug: 'upper-west-side', lat: 40.7870, lon: -73.9754, group: 'Manhattan', description: "Flanked by Central Park and the Hudson River, the Upper West Side catches westerly breezes that make it one of Manhattan's cooler neighborhoods." },
      { name: 'Harlem', slug: 'harlem', lat: 40.8116, lon: -73.9465, group: 'Manhattan', description: "Harlem's dense pavement and distance from major green spaces create strong heat island conditions in summer." },
      { name: 'Lower East Side', slug: 'lower-east-side', lat: 40.7157, lon: -73.9863, group: 'Manhattan', description: "The Lower East Side's low-rise blocks and proximity to the East River give it more river wind exposure than Midtown." },
      { name: 'SoHo', slug: 'soho', lat: 40.7233, lon: -74.0030, group: 'Manhattan', description: "SoHo's cast-iron buildings and cobblestone streets absorb significant heat in summer, making it one of Lower Manhattan's warmest neighborhoods." },
      { name: 'Tribeca', slug: 'tribeca', lat: 40.7163, lon: -74.0086, group: 'Manhattan', description: "Tribeca's Hudson River proximity provides refreshing summer breezes but amplifies wind chill in winter." },
      { name: 'Greenwich Village', slug: 'greenwich-village', lat: 40.7336, lon: -74.0027, group: 'Manhattan', description: "Greenwich Village's irregular street grid creates varied microclimates, with Hudson Street acting as a river wind corridor." },
      { name: 'Chelsea', slug: 'chelsea', lat: 40.7465, lon: -74.0014, group: 'Manhattan', description: "Chelsea's Hudson River frontage means steady westerly breezes year-round, strongest along the elevated High Line." },
      { name: 'Financial District', slug: 'financial-district', lat: 40.7074, lon: -74.0113, group: 'Manhattan', description: "At Manhattan's southern tip, the Financial District faces harbor winds from multiple directions, creating intense wind tunnels between towers." },
      { name: 'Washington Heights', slug: 'washington-heights', lat: 40.8448, lon: -73.9400, group: 'Manhattan', description: "One of Manhattan's highest elevations, Washington Heights is cooler on average and more exposed to northerly winds from the Hudson Valley." },
      { name: 'East Village', slug: 'east-village', lat: 40.7265, lon: -73.9815, group: 'Manhattan', description: "Dense low-rise blocks trap heat in summer while long north-south avenues create wind corridors on blustery days." },
      { name: "Hell's Kitchen", slug: 'hells-kitchen', lat: 40.7638, lon: -73.9918, group: 'Manhattan', description: "Hell's Kitchen faces the Hudson directly — wide cross streets funnel river winds east making it one of Midtown's breeziest neighborhoods." },
      { name: 'Inwood', slug: 'inwood', lat: 40.8677, lon: -73.9211, group: 'Manhattan', description: "At Manhattan's northern tip between two rivers, Inwood Hill Park provides wind shelter and keeps the area slightly cooler than surrounding blocks." },
      // Brooklyn
      { name: 'Williamsburg', slug: 'williamsburg', lat: 40.7081, lon: -73.9571, group: 'Brooklyn', description: "Williamsburg's East River waterfront creates a strong wind corridor facing Manhattan. Northeast winds funnel down the river in winter while summer brings occasional cooling breezes." },
      { name: 'Park Slope', slug: 'park-slope', lat: 40.6681, lon: -73.9800, group: 'Brooklyn', description: "Park Slope rises toward Prospect Park, which acts as a temperature buffer — streets near the park run cooler than the rest of the neighborhood." },
      { name: 'DUMBO', slug: 'dumbo', lat: 40.7033, lon: -73.9882, group: 'Brooklyn', description: "Beneath the Manhattan and Brooklyn Bridges with East River exposure on two sides, DUMBO is one of Brooklyn's most consistently windy spots." },
      { name: 'Coney Island', slug: 'coney-island', lat: 40.5755, lon: -73.9707, group: 'Brooklyn', description: "Coney Island experiences full Atlantic coastal weather — 5–10°F cooler than inland Brooklyn in summer, with harsh offshore winds and elevated nor'easter exposure in winter." },
      { name: 'Bay Ridge', slug: 'bay-ridge', lat: 40.6350, lon: -74.0200, group: 'Brooklyn', description: "Bay Ridge overlooks the Narrows with consistent harbor winds year-round. Its elevated terrain makes it breezier than lower Brooklyn." },
      { name: 'Bushwick', slug: 'bushwick', lat: 40.6944, lon: -73.9213, group: 'Brooklyn', description: "One of Brooklyn's more inland neighborhoods, Bushwick's wide industrial blocks retain heat and lack the park buffers of more central areas." },
      { name: 'Flatbush', slug: 'flatbush', lat: 40.6501, lon: -73.9496, group: 'Brooklyn', description: "Central Brooklyn's Flatbush sees hotter and more humid summers than the coastline, without the moderating ocean breezes of Coney Island." },
      { name: 'Crown Heights', slug: 'crown-heights', lat: 40.6694, lon: -73.9428, group: 'Brooklyn', description: "Crown Heights sits on a slight ridge near Prospect Park, which provides temperature moderation on hot days." },
      { name: 'Bed-Stuy', slug: 'bed-stuy', lat: 40.6872, lon: -73.9418, group: 'Brooklyn', description: "Bedford-Stuyvesant's dense residential blocks and distance from the water create classic urban heat island conditions." },
      { name: 'Greenpoint', slug: 'greenpoint', lat: 40.7242, lon: -73.9543, group: 'Brooklyn', description: "A peninsula between the East River and Newtown Creek, Greenpoint has waterfront exposure on two sides and little wind shelter from its low-rise industrial character." },
      { name: 'Sunset Park', slug: 'sunset-park', lat: 40.6459, lon: -74.0054, group: 'Brooklyn', description: "The elevated ridge along Shore Road faces New York Harbor with sweeping views and consistent harbor breezes that cool the park." },
      { name: 'Brighton Beach', slug: 'brighton-beach', lat: 40.5776, lon: -73.9614, group: 'Brooklyn', description: "Brighton Beach faces the Atlantic directly — afternoon sea breezes keep summers cool, while winter winds off the open ocean can be biting." },
      { name: 'Red Hook', slug: 'red-hook', lat: 40.6759, lon: -74.0092, group: 'Brooklyn', description: "Jutting into Upper New York Bay with water on three sides, Red Hook is one of Brooklyn's most weather-exposed neighborhoods." },
      { name: 'Bensonhurst', slug: 'bensonhurst', lat: 40.6010, lon: -73.9981, group: 'Brooklyn', description: "Southern Brooklyn's Bensonhurst occasionally catches ocean breezes from the south, but dense residential blocks buffer most wind." },
      // Queens
      { name: 'Flushing', slug: 'flushing', lat: 40.7675, lon: -73.8330, group: 'Queens', description: "Central-eastern Queens' Flushing sits away from major waterways, giving it more extreme temperatures than coastal neighborhoods." },
      { name: 'Astoria', slug: 'astoria', lat: 40.7722, lon: -73.9301, group: 'Queens', description: "Astoria faces the East River and the Hell Gate tidal confluence, producing notable river winds along the waterfront blocks." },
      { name: 'Jackson Heights', slug: 'jackson-heights', lat: 40.7557, lon: -73.8830, group: 'Queens', description: "Mid-Queens' Jackson Heights has typical inland urban conditions — dense blocks trap summer heat without waterfront relief." },
      { name: 'Jamaica', slug: 'jamaica', lat: 40.6923, lon: -73.8061, group: 'Queens', description: "Jamaica Bay to the south gives Jamaica some coastal influence, but the commercial downtown core remains a significant heat island." },
      { name: 'Forest Hills', slug: 'forest-hills', lat: 40.7185, lon: -73.8458, group: 'Queens', description: "Forest Hills and adjacent Forest Park create a green temperature buffer — streets near the park run noticeably cooler than Queens Boulevard." },
      { name: 'Long Island City', slug: 'long-island-city', lat: 40.7447, lon: -73.9485, group: 'Queens', description: "LIC's East River waterfront and growing tower cluster creates increasing wind tunnel effects similar to Midtown Manhattan." },
      { name: 'Bayside', slug: 'bayside', lat: 40.7624, lon: -73.7702, group: 'Queens', description: "Bayside's Long Island Sound proximity brings maritime air and cooling sea breezes that keep summer temperatures lower than central Queens." },
      { name: 'Rockaway Beach', slug: 'rockaway-beach', lat: 40.5862, lon: -73.8162, group: 'Queens', description: "NYC's only true ocean-facing beach community — a barrier island with the Atlantic to the south and Jamaica Bay to the north, 5–10°F cooler than inland Queens in summer." },
      { name: 'JFK Airport', slug: 'jfk-airport', lat: 40.6413, lon: -73.7781, group: 'Queens', description: "JFK's coastal location on Jamaica Bay means frequent fog, sea breezes, and wind shear that directly affect flight operations." },
      { name: 'Elmhurst', slug: 'elmhurst', lat: 40.7368, lon: -73.8801, group: 'Queens', description: "Central Queens' Elmhurst has no major waterfront exposure, giving it typical inland urban heat island conditions." },
      { name: 'Howard Beach', slug: 'howard-beach', lat: 40.6568, lon: -73.8455, group: 'Queens', description: "Sitting directly on Jamaica Bay, Howard Beach has strong coastal influence and low-lying terrain that saw major flooding during Sandy." },
      { name: 'Ridgewood', slug: 'ridgewood', lat: 40.7056, lon: -73.9041, group: 'Queens', description: "Ridgewood straddles the Queens-Brooklyn border on a modest ridge, with slightly better airflow and more tree cover than adjacent Bushwick." },
      // The Bronx
      { name: 'South Bronx', slug: 'south-bronx', lat: 40.8167, lon: -73.9174, group: 'The Bronx', description: "The South Bronx is among NYC's most heat-vulnerable areas — minimal tree cover and high impervious surface coverage drive intense heat island conditions." },
      { name: 'Pelham Bay', slug: 'pelham-bay', lat: 40.8545, lon: -73.8102, group: 'The Bronx', description: "Pelham Bay Park — NYC's largest — and its Long Island Sound coastline provide maritime air and sea breezes that cool this northeastern Bronx neighborhood." },
      { name: 'Fordham', slug: 'fordham', lat: 40.8610, lon: -73.8929, group: 'The Bronx', description: "Central Bronx' Fordham sits on moderate terrain away from waterways, with pronounced seasonal swings and urban heat in summer." },
      { name: 'Riverdale', slug: 'riverdale', lat: 40.8981, lon: -73.9120, group: 'The Bronx', description: "One of the Bronx's most elevated and wooded neighborhoods, Riverdale's tree canopy and Hudson River proximity keep it notably cooler than the southern Bronx." },
      { name: 'Mott Haven', slug: 'mott-haven', lat: 40.8067, lon: -73.9258, group: 'The Bronx', description: "Surrounded by the Harlem River, Mott Haven consistently ranks among NYC's hottest neighborhoods during heat waves due to extreme urban density." },
      { name: 'Throggs Neck', slug: 'throggs-neck', lat: 40.8244, lon: -73.8283, group: 'The Bronx', description: "A peninsula extending into Long Island Sound with water on three sides, Throggs Neck has persistent maritime breezes and moderate temperatures year-round." },
      { name: 'Concourse', slug: 'concourse', lat: 40.8367, lon: -73.9219, group: 'The Bronx', description: "The Grand Concourse boulevard acts as a wind channel through the otherwise dense residential fabric of central Bronx." },
      { name: 'Tremont', slug: 'tremont', lat: 40.8479, lon: -73.8983, group: 'The Bronx', description: "Tremont's proximity to Bronx Park provides some temperature moderation, though dense residential streets still concentrate heat in summer." },
      // Staten Island
      { name: 'St. George', slug: 'st-george', lat: 40.6437, lon: -74.0738, group: 'Staten Island', description: "St. George sits at Staten Island's northern tip facing New York Harbor, with ferry terminal winds and consistent harbor breezes year-round." },
      { name: 'Great Kills', slug: 'great-kills', lat: 40.5510, lon: -74.1502, group: 'Staten Island', description: "Great Kills' Raritan Bay exposure brings Atlantic coastal influence, with strong southerly winds during summer storms." },
      { name: 'Stapleton', slug: 'stapleton', lat: 40.6282, lon: -74.0754, group: 'Staten Island', description: "Facing the Kill van Kull strait, Stapleton has consistent tidal winds and low-lying waterfront terrain." },
      { name: 'New Dorp', slug: 'new-dorp', lat: 40.5731, lon: -74.1130, group: 'Staten Island', description: "Mid-island New Dorp gets coastal influence from the Atlantic to the southeast while wooded terrain provides natural windbreaks." },
      { name: 'Tottenville', slug: 'tottenville', lat: 40.5126, lon: -74.2518, group: 'Staten Island', description: "NYC's southernmost neighborhood, Tottenville is fully exposed to Raritan Bay and catches the full force of southerly storms and nor'easters." },
      { name: 'Snug Harbor', slug: 'snug-harbor', lat: 40.6424, lon: -74.1018, group: 'Staten Island', description: "Snug Harbor Cultural Center's grounds and trees buffer Kill van Kull winds and provide cooler summer conditions than surrounding streets." },
    ],
  },
  {
    name: 'London',
    slug: 'london',
    country: 'United Kingdom',
    flag: '🇬🇧',
    lat: 51.5074,
    lon: -0.1278,
    timezone: 'Europe/London',
    description: "London's weather is shaped by its temperate maritime climate — mild, cloudy, and famously unpredictable. The Thames corridor funnels westerly winds through the city, while parks like Hyde Park and Hampstead Heath create localized cooling effects. Inner East London stays warmer year-round from the urban heat island, while elevated areas like Hampstead experience notably cooler and wetter conditions.",
    districts: [
      { name: 'Shoreditch', slug: 'shoreditch', lat: 51.5225, lon: -0.0777, group: 'East London', description: "Shoreditch's dense low-rise urban fabric traps heat in summer. Its location in East London means it misses the cooling westerly breezes that reach Hyde Park." },
      { name: 'Canary Wharf', slug: 'canary-wharf', lat: 51.5054, lon: -0.0235, group: 'East London', description: "Canary Wharf's cluster of skyscrapers creates wind tunnels along its elevated walkways. The Thames bend on three sides brings river winds year-round." },
      { name: 'Chelsea', slug: 'chelsea', lat: 51.4871, lon: -0.1713, group: 'West London', description: "Chelsea's Thames Embankment exposure and wealthy tree-lined streets give it a cooler character than denser central London neighborhoods." },
      { name: 'Notting Hill', slug: 'notting-hill', lat: 51.5131, lon: -0.2006, group: 'West London', description: "Notting Hill sits on slightly elevated ground in West London, catching westerly winds that sweep in from the Atlantic across Hyde Park." },
      { name: 'Soho', slug: 'soho', lat: 51.5137, lon: -0.1344, group: 'Central London', description: "Dense and lively, Soho's narrow streets trap heat and exhaust. It's one of Central London's warmest neighborhoods in summer." },
      { name: 'Covent Garden', slug: 'covent-garden', lat: 51.5118, lon: -0.1240, group: 'Central London', description: "Covent Garden's pedestrianized piazza and street level activity make weather particularly noticeable — the open square channels wind across the market." },
      { name: 'Camden', slug: 'camden', lat: 51.5390, lon: -0.1426, group: 'North London', description: "Camden's position on the Regent's Canal and proximity to Hampstead Heath gives it more varied weather than the city center." },
      { name: 'Hackney', slug: 'hackney', lat: 51.5450, lon: -0.0553, group: 'East London', description: "Hackney benefits from Victoria Park and the Lee Valley green corridor, which moderate temperatures compared to the densest parts of East London." },
      { name: 'Brixton', slug: 'brixton', lat: 51.4613, lon: -0.1156, group: 'South London', description: "Brixton in South London has slightly less rainfall than north-facing slopes and benefits from a more sheltered position relative to prevailing westerlies." },
      { name: 'Islington', slug: 'islington', lat: 51.5361, lon: -0.1033, group: 'North London', description: "Islington's gentle northward rise means slightly cooler and breezier conditions than the Thames-side neighborhoods to its south." },
      { name: 'Mayfair', slug: 'mayfair', lat: 51.5100, lon: -0.1477, group: 'Central London', description: "Mayfair's wide tree-lined streets and proximity to Hyde Park give it a more pleasant microclimate than denser parts of Central London." },
      { name: 'Kensington', slug: 'kensington', lat: 51.5000, lon: -0.1910, group: 'West London', description: "Kensington Palace Gardens and Hyde Park form a large green buffer that keeps Kensington noticeably cooler than inner London in summer." },
      { name: 'Greenwich', slug: 'greenwich', lat: 51.4826, lon: 0.0077, group: 'South East London', description: "Greenwich's riverside position and the open expanse of Greenwich Park create a unique microclimate — river fog is common in autumn mornings." },
      { name: 'Westminster', slug: 'westminster', lat: 51.4994, lon: -0.1248, group: 'Central London', description: "Westminster sits at the Thames bend with St James's Park nearby providing a green buffer. River mists are common in winter mornings." },
      { name: 'Hammersmith', slug: 'hammersmith', lat: 51.4927, lon: -0.2239, group: 'West London', description: "Hammersmith's Thames riverside location exposes it to tidal winds, and its open riverfront feels several degrees colder than nearby inland streets in winter." },
      { name: 'Richmond', slug: 'richmond', lat: 51.4613, lon: -0.3037, group: 'South West London', description: "Richmond Park's enormous open space and Thames proximity make Richmond one of Greater London's coolest and most weather-exposed suburbs." },
      { name: 'Wimbledon', slug: 'wimbledon', lat: 51.4214, lon: -0.2064, group: 'South West London', description: "Wimbledon's elevated common and tennis-famous courts sit on higher ground that catches more wind and rainfall than the Thames valley below." },
      { name: 'Stratford', slug: 'stratford', lat: 51.5416, lon: -0.0033, group: 'East London', description: "Stratford's Olympic Park opened up large green spaces that have improved air quality and slightly moderated temperatures in this formerly industrial area." },
      { name: 'Southwark', slug: 'southwark', lat: 51.5034, lon: -0.0898, group: 'South East London', description: "Southwark's South Bank riverside walk faces north across the Thames, catching prevailing westerlies and experiencing significant temperature drop at the riverside compared to inland streets." },
      { name: 'Bermondsey', slug: 'bermondsey', lat: 51.4985, lon: -0.0742, group: 'South East London', description: "Bermondsey's former industrial riverside character means relatively low tree cover and some heat retention, though its Thames-adjacent location brings river breezes." },
    ],
  },
  {
    name: 'Tokyo',
    slug: 'tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    lat: 35.6762,
    lon: 139.6503,
    timezone: 'Asia/Tokyo',
    description: "Tokyo's weather is defined by four dramatic seasons — brutally hot and humid summers driven by the Pacific high pressure, mild cherry-blossom springs, typhoon-prone autumns, and cold, dry winters with occasional heavy snowfall. Tokyo Bay moderates coastal temperatures slightly, while the elevated western districts (Hachioji, Okutama) run significantly cooler. The dense urban core creates one of the world's most intense heat island effects.",
    districts: [
      { name: 'Shibuya', slug: 'shibuya', lat: 35.6580, lon: 139.7016, group: 'Central Tokyo', description: "Shibuya's iconic crossing and dense commercial district trap heat intensely in summer. The valley position between hills makes it one of central Tokyo's warmer spots." },
      { name: 'Shinjuku', slug: 'shinjuku', lat: 35.6896, lon: 139.6917, group: 'Central Tokyo', description: "Shinjuku's skyscraper west side and dense east side create varied microclimates. The towering buildings funnel winds and the dense nightlife district stays warm well into autumn evenings." },
      { name: 'Ginza', slug: 'ginza', lat: 35.6717, lon: 139.7650, group: 'Central Tokyo', description: "Ginza's upscale paved blocks near Tokyo Bay experience sea breezes on summer afternoons, providing some relief from the intense urban heat." },
      { name: 'Akihabara', slug: 'akihabara', lat: 35.7022, lon: 139.7745, group: 'Central Tokyo', description: "Akihabara's dense electronics district in the Kanda River lowlands is one of Tokyo's warmer areas — surrounded by concrete with minimal green space." },
      { name: 'Asakusa', slug: 'asakusa', lat: 35.7148, lon: 139.7967, group: 'East Tokyo', description: "Asakusa sits near the Sumida River, which provides occasional breezes. The traditional low-rise character around Senso-ji Temple makes it feel more open than commercial districts." },
      { name: 'Roppongi', slug: 'roppongi', lat: 35.6604, lon: 139.7292, group: 'Central Tokyo', description: "Roppongi's elevated terrain on the Musashino Plateau edge gives it slightly better ventilation than Tokyo's lowland districts, though the dense nightlife area retains significant heat." },
      { name: 'Harajuku', slug: 'harajuku', lat: 35.6702, lon: 139.7027, group: 'Central Tokyo', description: "Harajuku's position adjacent to Yoyogi Park provides significant temperature moderation — the park keeps surrounding streets measurably cooler on hot summer days." },
      { name: 'Ikebukuro', slug: 'ikebukuro', lat: 35.7295, lon: 139.7109, group: 'North Tokyo', description: "Ikebukuro's major shopping and transport hub sits in a slight basin, giving it hot and humid summers with less ventilation than hilltop neighborhoods." },
      { name: 'Ueno', slug: 'ueno', lat: 35.7140, lon: 139.7741, group: 'North East Tokyo', description: "Ueno Park's forest and Shinobazu Pond provide cooling evaporation effects, making the park-side streets noticeably cooler than surrounding commercial areas." },
      { name: 'Odaiba', slug: 'odaiba', lat: 35.6269, lon: 139.7752, group: 'Tokyo Bay', description: "Odaiba's artificial island in Tokyo Bay experiences true maritime weather — sea breezes keep it cooler in summer than the mainland, and bay fog is common in autumn." },
      { name: 'Marunouchi', slug: 'marunouchi', lat: 35.6812, lon: 139.7671, group: 'Central Tokyo', description: "Tokyo's business core near the Imperial Palace. The Palace grounds and moat provide a rare green buffer that moderates temperatures in an otherwise dense urban canyon." },
      { name: 'Nakameguro', slug: 'nakameguro', lat: 35.6438, lon: 139.6992, group: 'Central Tokyo', description: "The Meguro River running through Nakameguro creates a cooling evaporative effect — riverside streets feel noticeably cooler than parallel blocks set back from the canal." },
      { name: 'Shimokitazawa', slug: 'shimokitazawa', lat: 35.6614, lon: 139.6679, group: 'West Tokyo', description: "Shimokitazawa's low-rise indie character and elevated position on the Musashino Plateau give it better natural ventilation than Tokyo's valley districts." },
      { name: 'Daikanyama', slug: 'daikanyama', lat: 35.6485, lon: 139.7033, group: 'Central Tokyo', description: "Elevated Daikanyama sits on a hill above Nakameguro with tree-lined streets and lower density than adjacent neighborhoods, resulting in slightly cooler conditions." },
      { name: 'Minato', slug: 'minato', lat: 35.6581, lon: 139.7514, group: 'Central Tokyo', description: "Home to embassies and Tokyo Tower, Minato's mix of high-rises and mid-rise buildings along Tokyo Bay creates variable wind patterns." },
      { name: 'Sumida', slug: 'sumida', lat: 35.7108, lon: 139.8014, group: 'East Tokyo', description: "Sumida's riverside position along the Sumida River provides consistent breezes and the river's presence moderates summer temperatures compared to inland East Tokyo." },
      { name: 'Koenji', slug: 'koenji', lat: 35.7053, lon: 139.6496, group: 'West Tokyo', description: "Koenji's elevated position along the old Chuo Line corridor with relatively low density and good tree coverage makes it one of western Tokyo's more comfortable summer neighborhoods." },
      { name: 'Akasaka', slug: 'akasaka', lat: 35.6742, lon: 139.7372, group: 'Central Tokyo', description: "Akasaka's government and hotel district on elevated terrain above the Sotobori moat benefits from hill breezes and proximity to Hie Shrine's wooded grounds." },
      { name: 'Omotesando', slug: 'omotesando', lat: 35.6652, lon: 139.7120, group: 'Central Tokyo', description: "Omotesando's famous zelkova tree-lined boulevard creates a rare natural cooling corridor in central Tokyo, with the tree canopy reducing summer temperatures significantly." },
      { name: 'Tsukiji', slug: 'tsukiji', lat: 35.6654, lon: 139.7707, group: 'Central Tokyo', description: "Tsukiji's bayside location near the old fish market brings Tokyo Bay sea breezes on summer afternoons, offering some relief from inland heat." },
    ],
  },
  {
    name: 'Paris',
    slug: 'paris',
    country: 'France',
    flag: '🇫🇷',
    lat: 48.8566,
    lon: 2.3522,
    timezone: 'Europe/Paris',
    description: "Paris has a temperate oceanic climate influenced by Atlantic weather systems — mild winters, warm summers, and rainfall spread throughout the year. The Seine acts as a temperature moderator and morning fog corridor in autumn. The city's densely built Haussmann-era blocks retain heat effectively, and Paris experiences Europe's most intense urban heat island effects during summer heat waves that occasionally become deadly.",
    districts: [
      { name: 'Le Marais', slug: 'le-marais', lat: 48.8566, lon: 2.3522, group: 'Right Bank', description: "Le Marais's narrow medieval streets between stone buildings create intense heat islands in summer and funnel biting cold winds in winter." },
      { name: 'Montmartre', slug: 'montmartre', lat: 48.8867, lon: 2.3431, group: 'North Paris', description: "Montmartre's hilltop position — the highest point in Paris — means cooler temperatures, stronger winds, and more frequent morning fog than the city below." },
      { name: 'Saint-Germain', slug: 'saint-germain', lat: 48.8533, lon: 2.3340, group: 'Left Bank', description: "Saint-Germain-des-Prés on the Left Bank benefits from proximity to Luxembourg Gardens, whose tree canopy lowers summer temperatures noticeably." },
      { name: 'Bastille', slug: 'bastille', lat: 48.8533, lon: 2.3692, group: 'Right Bank', description: "Bastille's central plaza and radiating boulevards channel winds from multiple directions, making it breezier than the surrounding narrow streets." },
      { name: 'Champs-Élysées', slug: 'champs-elysees', lat: 48.8698, lon: 2.3079, group: 'Right Bank', description: "The wide Champs-Élysées boulevard and adjacent Tuileries and Champs de Mars gardens create a significant green and open corridor that moderates temperatures in western Paris." },
      { name: 'Belleville', slug: 'belleville', lat: 48.8719, lon: 2.3793, group: 'East Paris', description: "Belleville's hillside position in northeast Paris gives it slightly cooler and breezier conditions than the Seine valley, with frequent cloud formation on the slope." },
      { name: 'Latin Quarter', slug: 'latin-quarter', lat: 48.8497, lon: 2.3483, group: 'Left Bank', description: "The Latin Quarter's dense student neighborhood sits on gentle elevation with Luxembourg Gardens to the west providing a welcome temperature buffer in summer." },
      { name: 'Pigalle', slug: 'pigalle', lat: 48.8836, lon: 2.3385, group: 'North Paris', description: "Pigalle sits at the foot of Montmartre hill where cold air from the heights drains downward on calm clear nights, creating a slight temperature inversion." },
      { name: 'Opéra', slug: 'opera', lat: 48.8717, lon: 2.3316, group: 'Right Bank', description: "The Grands Boulevards around the Opéra are wide and wind-exposed. The dense commercial character retains heat, but large intersections allow some ventilation." },
      { name: 'République', slug: 'republique', lat: 48.8675, lon: 2.3634, group: 'Right Bank', description: "Place de la République's large open square is one of Paris's most wind-exposed public spaces — the wide plaza amplifies breezes regardless of direction." },
      { name: 'Nation', slug: 'nation', lat: 48.8482, lon: 2.3960, group: 'East Paris', description: "Nation's large circular plaza in eastern Paris channels winds from multiple avenues. The Vincennes woods to the east provide cooling air flow in summer evenings." },
      { name: 'Canal Saint-Martin', slug: 'canal-saint-martin', lat: 48.8712, lon: 2.3625, group: 'Right Bank', description: "The Canal Saint-Martin's tree-lined banks create a cooling evaporative corridor through northeastern Paris, noticeably fresher than adjacent inland streets." },
      { name: 'Châtelet', slug: 'chatelet', lat: 48.8589, lon: 2.3469, group: 'Central Paris', description: "Châtelet-Les Halles at Paris's geographic center is surrounded by dense Haussmann blocks that amplify summer heat. The underground complex adds thermal mass." },
      { name: 'Bercy', slug: 'bercy', lat: 48.8392, lon: 2.3823, group: 'South East Paris', description: "Bercy Park along the Seine in eastern Paris creates a riverside green corridor with good ventilation and a cooler microclimate than surrounding dense blocks." },
      { name: 'Batignolles', slug: 'batignolles', lat: 48.8847, lon: 2.3238, group: 'North West Paris', description: "The Batignolles neighborhood and its park in northwest Paris offer a village-like respite with enough tree coverage to buffer the urban heat island." },
      { name: 'Buttes-Chaumont', slug: 'buttes-chaumont', lat: 48.8800, lon: 2.3819, group: 'North East Paris', description: "Buttes-Chaumont Park's dramatic hills create one of northeast Paris's coolest microclimates, with lake-generated humidity and shade from dense mature trees." },
      { name: 'Oberkampf', slug: 'oberkampf', lat: 48.8635, lon: 2.3749, group: 'East Paris', description: "Oberkampf's lively eastern neighborhood sits on flat terrain between canals and parks, with typical Haussmann block heat retention in summer." },
      { name: 'Boulogne', slug: 'boulogne', lat: 48.8352, lon: 2.2397, group: 'West Paris', description: "Adjacent to the vast Bois de Boulogne, this western suburb benefits enormously from the forest's cooling effect — among the freshest summer microclimates in greater Paris." },
      { name: 'Vincennes', slug: 'vincennes', lat: 48.8479, lon: 2.4388, group: 'East Paris', description: "Vincennes borders the Bois de Vincennes, Paris's eastern forest, which keeps local temperatures several degrees lower than the city center on hot summer days." },
      { name: 'Saint-Denis', slug: 'saint-denis', lat: 48.9362, lon: 2.3574, group: 'North Paris', description: "Saint-Denis north of Paris experiences more extreme weather than the sheltered city center — stronger winds, harder frosts in winter, and more heat in summer without Haussmann density buffering." },
    ],
  },
  {
    name: 'Dubai',
    slug: 'dubai',
    country: 'United Arab Emirates',
    flag: '🇦🇪',
    lat: 25.2048,
    lon: 55.2708,
    timezone: 'Asia/Dubai',
    description: "Dubai has a hot desert climate with virtually no rainfall and searing summers where temperatures routinely exceed 40°C (104°F) with intense humidity from the Persian Gulf. The Gulf moderates winter temperatures and brings morning sea fog. Summer heat is compounded by the urban heat island in dense downtown areas, while coastal neighborhoods benefit from sea breezes that can make outdoor conditions more bearable. Shamal winds from the north bring sandstorms and dust haze spring through summer.",
    districts: [
      { name: 'Downtown Dubai', slug: 'downtown-dubai', lat: 25.1972, lon: 55.2744, group: 'Central Dubai', description: "The Burj Khalifa creates powerful updrafts and wind shear at high altitude. At street level, the dense skyscraper cluster traps heat, making Downtown Dubai among the UAE's most extreme urban heat islands." },
      { name: 'Dubai Marina', slug: 'dubai-marina', lat: 25.0805, lon: 55.1403, group: 'West Dubai', description: "Dubai Marina's water channel running through the development provides evaporative cooling and sea breezes from the Gulf just minutes away, making it more livable than inland neighborhoods in summer." },
      { name: 'Jumeirah', slug: 'jumeirah', lat: 25.2048, lon: 55.2708, group: 'Coastal Dubai', description: "Jumeirah's beachfront position on the Gulf ensures consistent sea breezes that significantly reduce the apparent heat compared to inland neighborhoods." },
      { name: 'Palm Jumeirah', slug: 'palm-jumeirah', lat: 25.1124, lon: 55.1390, group: 'Coastal Dubai', description: "The Palm peninsula is surrounded by Gulf waters on all sides, bringing sea breezes from every direction that help offset the intense solar radiation." },
      { name: 'Business Bay', slug: 'business-bay', lat: 25.1870, lon: 55.2635, group: 'Central Dubai', description: "Business Bay's Dubai Canal provides some water-adjacent cooling but the dense commercial towers create significant heat retention and wind tunnel effects." },
      { name: 'Deira', slug: 'deira', lat: 25.2697, lon: 55.3094, group: 'Old Dubai', description: "Historic Deira on the Dubai Creek has lower building heights than downtown, with the Creek providing some evaporative cooling and traditional wind tower (barjeel) architecture designed to catch breezes." },
      { name: 'DIFC', slug: 'difc', lat: 25.2138, lon: 55.2800, group: 'Central Dubai', description: "The Dubai International Financial Centre's glass tower cluster creates intense heat reflection and wind shear. The elevated indoor walkways somewhat insulate pedestrians from outdoor extremes." },
      { name: 'JBR', slug: 'jbr', lat: 25.0762, lon: 55.1317, group: 'West Dubai', description: "Jumeirah Beach Residence's open beachfront and Gulf breezes make it one of Dubai's most pleasant outdoor districts in winter and transition seasons." },
      { name: 'Bur Dubai', slug: 'bur-dubai', lat: 25.2543, lon: 55.2967, group: 'Old Dubai', description: "Historic Bur Dubai's traditional low-rise buildings along the Creek were designed with passive cooling in mind. The Creek provides evaporative cooling and wind funneling." },
      { name: 'Karama', slug: 'karama', lat: 25.2314, lon: 55.3067, group: 'Central Dubai', description: "Karama's dense mid-rise residential blocks retain intense heat with limited green space and minimal sea breeze penetration this far inland." },
      { name: 'Internet City', slug: 'internet-city', lat: 25.0964, lon: 55.1575, group: 'West Dubai', description: "Dubai Internet City's campus-style development near the Gulf benefits from sea breezes and slightly more open planning than the downtown core." },
      { name: 'Media City', slug: 'media-city', lat: 25.1027, lon: 55.1676, group: 'West Dubai', description: "Adjacent to Internet City, Media City's open campus layout near the coast allows Gulf breezes to penetrate and moderate summer heat." },
      { name: 'Al Quoz', slug: 'al-quoz', lat: 25.1502, lon: 55.2255, group: 'Central Dubai', description: "Al Quoz's industrial and arts district in central Dubai has minimal tree cover and high thermal mass from warehouses, creating intense heat retention." },
      { name: 'Dubai Creek', slug: 'dubai-creek', lat: 25.2631, lon: 55.3006, group: 'Old Dubai', description: "The historic Dubai Creek waterway provides evaporative cooling along its banks, making waterfront dining and walking more comfortable than inland streets." },
      { name: 'Mirdif', slug: 'mirdif', lat: 25.2264, lon: 55.4147, group: 'East Dubai', description: "Mirdif's suburban residential character in eastern Dubai, distant from the Gulf, means hotter and more arid conditions with minimal sea breeze influence." },
    ],
  },
  {
    name: 'Sydney',
    slug: 'sydney',
    country: 'Australia',
    flag: '🇦🇺',
    lat: -33.8688,
    lon: 151.2093,
    timezone: 'Australia/Sydney',
    description: "Sydney enjoys a temperate oceanic climate with warm summers, mild winters, and rainfall throughout the year. Sydney Harbour and the Pacific Ocean create significant coastal influence — sea breezes (locally called the 'Southerly Buster') arrive in summer afternoons and dramatically cool the city within minutes. Western suburbs are 5–10°C hotter in summer than coastal areas, and extreme fire weather during inland heat waves creates dangerous conditions.",
    districts: [
      { name: 'CBD', slug: 'cbd', lat: -33.8688, lon: 151.2093, group: 'Inner Sydney', description: "Sydney's CBD sits on the harbour's south shore where sea breezes arrive reliably in summer afternoons. The dense tower core creates wind tunnels between skyscrapers." },
      { name: 'Surry Hills', slug: 'surry-hills', lat: -33.8864, lon: 151.2094, group: 'Inner East', description: "Surry Hills' dense Victorian terrace rows trap heat in summer. Its inland position from the Harbour means sea breezes arrive later and weaker than in CBD." },
      { name: 'Newtown', slug: 'newtown', lat: -33.8980, lon: 151.1800, group: 'Inner West', description: "Newtown's inner west position means it bakes in summer before the afternoon southerly arrives. King Street's urban canyon amplifies heat in the middle of the day." },
      { name: 'Bondi Beach', slug: 'bondi-beach', lat: -33.8914, lon: 151.2743, group: 'Eastern Suburbs', description: "Bondi's ocean beach faces southeast — it catches the southerly buster head-on, making it one of Sydney's most dramatically weather-shifted spots when the sea change arrives." },
      { name: 'Manly', slug: 'manly', lat: -33.7969, lon: 151.2877, group: 'Northern Beaches', description: "Manly's isthmus between the Harbour and Pacific Ocean gives it genuine coastal weather from two directions — harbour breezes and open ocean swell conditions." },
      { name: 'Paddington', slug: 'paddington', lat: -33.8835, lon: 151.2290, group: 'Inner East', description: "Paddington's elevated ridge between the CBD and Bondi catches sea breezes from the east while its Victorian terrace density retains daytime heat." },
      { name: 'Glebe', slug: 'glebe', lat: -33.8801, lon: 151.1870, group: 'Inner West', description: "Glebe's peninsula between Blackwattle Bay and Rozelle Bay gives it water exposure on two sides, with harbour breezes reaching the foreshore." },
      { name: 'Darlinghurst', slug: 'darlinghurst', lat: -33.8775, lon: 151.2215, group: 'Inner East', description: "Darlinghurst's elevated terrain between the CBD and inner east provides good ventilation, and Oxford Street acts as an east-west wind corridor." },
      { name: 'Pyrmont', slug: 'pyrmont', lat: -33.8720, lon: 151.1970, group: 'Inner Sydney', description: "Pyrmont's Darling Harbour and Blackwattle Bay waterfront means consistent harbour breezes. The redeveloped peninsula has become significantly greener and cooler than its industrial past." },
      { name: 'North Sydney', slug: 'north-sydney', lat: -33.8401, lon: 151.2072, group: 'North Shore', description: "North Sydney's harbour-facing commercial district gets strong northerly winds off the Harbour. The Harbour Bridge creates local turbulence on windy days." },
      { name: 'Parramatta', slug: 'parramatta', lat: -33.8148, lon: 151.0017, group: 'Western Sydney', description: "Parramatta in Sydney's west is the classic example of Sydney's urban heat island — regularly 5–10°C hotter than coastal suburbs during summer heat waves." },
      { name: 'Chatswood', slug: 'chatswood', lat: -33.7962, lon: 151.1836, group: 'North Shore', description: "Chatswood's north shore position catches northern sea breezes off Middle Harbour, keeping it measurably cooler than western suburbs in summer." },
      { name: 'Mosman', slug: 'mosman', lat: -33.8265, lon: 151.2453, group: 'North Shore', description: "Mosman's position on a harbour headland with water on three sides gives it exceptional harbour breezes and among Sydney's most pleasant summer microclimates." },
      { name: 'Balmain', slug: 'balmain', lat: -33.8604, lon: 151.1792, group: 'Inner West', description: "Balmain's peninsula into the Parramatta River gives it water exposure on three sides, with consistent harbour breezes and cooling sea air." },
      { name: 'Redfern', slug: 'redfern', lat: -33.8929, lon: 151.2042, group: 'Inner South', description: "Redfern's flat inland position south of the CBD means heat accumulates without much coastal ventilation. The suburb is warming faster than coastal areas due to densification." },
    ],
  },
]

export function getCity(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug)
}

export function getDistrict(citySlug: string, districtSlug: string): District | undefined {
  return getCity(citySlug)?.districts.find((d) => d.slug === districtSlug)
}
